### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by randinterval** [justeat/JUSTOKRs#1]
Hi,
When i run ember server command i get the following error: Any idea what might be the issue?

A new version of ember-cli is available (1.13.12). To install it, type ember update.
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at module.exports (/root/okr/config/environment.js:28:40)
    at Project.config (/root/okr/node_modules/ember-cli/lib/models/project.js:174:52)
    at Class.module.exports.Command.extend.run (/root/okr/node_modules/ember-cli/lib/commands/serve.js:32:29)
    at Class.<anonymous> (/root/okr/node_modules/ember-cli/lib/models/command.js:136:17)
    at lib$rsvp$$internal$$tryCatch (/root/okr/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/root/okr/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/root/okr/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/root/okr/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)

**Comment by randinterval** [comment]
So, I've managed to install it but when i open in browser it keeps redirecting between main and /login url..weird.

**Comment by randinterval** [comment]
Hi, I've managed to install it at http://104.238.191.107:4200/ but it keeps redirecting to /login ..Any idea what could be the issue? @danielrichardson  @petemounce  @AnthonySteele  @smnbss  @byronp

**Comment by gordonbaz** [comment]
Hi there,
 I'm the chap who put JUSTOKRs together - I'm on holiday right now but will come back to you next Wednesday

Thanks,  
  Gordon

**Comment by gordonbaz** [comment]
Hi @randinterval, 
  The JUST OKRS tool is currently set up to authenticate and authorise with ADFS (the URL specified by the OKR_AD_REDIRECT environment variable.  Do you have an AD server to authenticate to?  

If not, an earlier version of the tool used basic Ember Simple Auth (https://github.com/simplabs/ember-simple-auth) and I can work out some recommendations on changes needed to use that again.

Thanks,
  Gordon

**Comment by randinterval** [comment]
Hi Gordon,
Thanks for the reply. I don't have ADFS server currently..What would be needed to swap that with Ember Simple Auth?Also, is the earlier version of the app which used Ember Simple Auth still available for download?

**Comment by gordonbaz** [comment]
Hi Saad,
  I've started looking into it but as with many things A&A based it's not simple.  The old commit is not available in the public repo and will need some work to incorporate

I've put together the following notes that explain how things work - (at least) the items in **bold** will need to be changed to work with stock Ember Simple Auth.  I'll try to find some time to change the code so that you can toggle whether AD or Ember Simple Auth is used on a per install basis in the next couple of weeks - alternatively if you have some bandwidth and would like to make a change I could help with guidance & review ...

i) Homepage
/routes/index.js
if the session.isAuthenticated cookie is set (since the user has already logged in) then
transition to summary page
 else
transition to login - go to ii)

ii) Login
**/routes/login.js**
1) transition to ADFS login page
2) user will provide their credentials and if correct ADFS will transition to
3) /api/api_auth_adfs/adfs_login - updates DB with data from ADFS and redirects to
4) /ember/login.js with a 302, including identification parameter (the token provided by ADFS).  This will transition to iii)

**Changes needed:**
* Show Simple Auth login page rather than redirecting to AD login page

iii) Authentication
Ember calls **api/api_auth_adfs/adfsCheck**
     called because that's the token endpoint for simpleAuth set in /config/environment.js
     NB. probably used to be /token
if a user exists who
     a) has the token passed to the function
     b) the token is still active (< 1 day)
     then return the details of that user
     routes/application.js/sessionAuthenticationSuceeded will transition the user to the summary page at this point
else return an "expired token" error
routes/application.js/sessionAuthenticationFailed will transition the user to the login page at this point - go to ii)

**Changes Needed**
Replace with non AD logic

iv) Authorisation
/api/api_auth_adfs/verifyToken
Used by any node database procedure as it's the strategy used by Passport i.e. every time apiCommon.passport.authenticate is called this routine will be called
If user exists for token passed and token is not expired
     return scope for user
else
     return invalid or expired user
          routes/application.js/sessionAuthenticationFailed will transition the user to the login page at this point - go to ii)

**Comment by wyattbenno777** [comment]
Hello, 
Simple auth would make this much more useful. Any idea when that may be available?

Thank you,

**Comment by gordonbaz** [comment]
Hi there,
  I'm working on an updated version that will allow you to choose whether to use ADFS or Ember Simple Auth authentication. It's working basically but needs more testing, will aim to release next week ...

Thanks,
  Gordon

**Comment by gordonbaz** [comment]
@randinterval @wyattbenno777 I've published v1.7.7 that includes the ability to use Ember Simple Auth or ADFS for authentication.  Please give it a go and let me know if you have any questions

Thanks
